[versions]
kotlin = "2.2.21"
junit5 = "5.14.1"
assertj = "3.27.6"
mockk = "1.14.6"
archunit = "1.4.1"
ktlint = "12.3.0"
sonarqube = "6.2.0.5505"

# TreeSitter
tree-sitter = "0.25.3"
tree-sitter-typescript = "0.23.2"
tree-sitter-javascript = "0.23.1"
tree-sitter-kotlin = "0.3.8.1"
tree-sitter-java = "0.23.4"
tree-sitter-csharp = "0.23.1"
tree-sitter-cpp = "0.23.4"
tree-sitter-c = "0.23.2"
tree-sitter-python = "0.23.4"
tree-sitter-go = "0.23.3"
tree-sitter-php = "0.23.11"
tree-sitter-ruby = "0.23.1"
tree-sitter-swift = "0.5.0"
tree-sitter-objc = "main"
tree-sitter-bash = "0.23.3"
tree-sitter-vue = "0.2.1a"

[libraries]
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit5" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit5" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit5" }
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
archunit-junit5 = { group = "com.tngtech.archunit", name = "archunit-junit5", version.ref = "archunit" }

treesitter = { group = "io.github.bonede", name = "tree-sitter", version.ref = "tree-sitter" }
treesitter-typescript = { group = "io.github.bonede", name = "tree-sitter-typescript", version.ref = "tree-sitter-typescript" }
treesitter-javascript = { group = "io.github.bonede", name = "tree-sitter-javascript", version.ref = "tree-sitter-javascript" }
treesitter-kotlin = { group = "io.github.bonede", name = "tree-sitter-kotlin", version.ref = "tree-sitter-kotlin" }
treesitter-java = { group = "io.github.bonede", name = "tree-sitter-java", version.ref = "tree-sitter-java" }
treesitter-csharp = { group = "io.github.bonede", name = "tree-sitter-c-sharp", version.ref = "tree-sitter-csharp" }
treesitter-cpp = { group = "io.github.bonede", name = "tree-sitter-cpp", version.ref = "tree-sitter-cpp" }
treesitter-c = { group = "io.github.bonede", name = "tree-sitter-c", version.ref = "tree-sitter-c" }
treesitter-python = { group = "io.github.bonede", name = "tree-sitter-python", version.ref = "tree-sitter-python" }
treesitter-go = { group = "io.github.bonede", name = "tree-sitter-go", version.ref = "tree-sitter-go" }
treesitter-php = { group = "io.github.bonede", name = "tree-sitter-php", version.ref = "tree-sitter-php" }
treesitter-ruby = { group = "io.github.bonede", name = "tree-sitter-ruby", version.ref = "tree-sitter-ruby" }
treesitter-swift = { group = "io.github.bonede", name = "tree-sitter-swift", version.ref = "tree-sitter-swift" }
treesitter-objc = { group = "io.github.bonede", name = "tree-sitter-objc", version.ref = "tree-sitter-objc" }
treesitter-bash = { group = "io.github.bonede", name = "tree-sitter-bash", version.ref = "tree-sitter-bash" }
treesitter-vue = { group = "io.github.bonede", name = "tree-sitter-vue", version.ref = "tree-sitter-vue" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
